### ISSUE TITLE
Splash and Auth

### ISSUE THREAD

**Issue by javiermortiz** [joshsomthin/hosthouse#8]
Splash is looking great!

- [x] Once you are displaying your spots and style them you are pretty much done with it.

Auth
- [x] I would add a margin between the log in and sign up buttons.
- [x] The sign up modal needs more padding on the bottom.
- [x] The logout dropdown needs more styling, the dropdown should be on a different position than the navbar with a box around it, remove the decorators for the li and the a tags.

**Comment by joshsomthin** [comment]
all issues fixed.
